# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ea774170bb4917a78fd09d61711113671aada36f78c5d85ed1c8a88b33e8507a0e00e1948933e9b2fd2aeef2308447dc33a39f74fb5cc6b9796e07434e29a8b6

test:
  secret_key_base: ffd70719847cc36926bfcb4228f6b80bce6c07d39ddd48807ebda6ad9770ca541ac6cb04cde3fa337eeb02eadd4cd936b0dd8d203bae972526654e649e87f20f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
